name: Dev env CI
on:
  push:
    branches:
      - main
jobs:
  web-workflow:
    uses: ./.github/workflows/web_workflow.yml
  apk-workflow:
    uses: ./.github/workflows/apk_workflow.yml
  ios-workflow:
    uses: ./.github/workflows/ios_workflow.yml
