name: Ios workflow

on:
  workflow_call:

jobs:
  build:
    name: Build Flutter App
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get dependencies
        run: flutter channel beta
      - run: flutter upgrade
      - run: flutter pub get
      - run: flutter config --enable-ios
      - run: flutter create .
      - run: flutter build ios -t lib/main_dev.dart --release --no-codesign
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios_build
          path: build/ios

  deploy:
    name: Deploy app
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/download-artifact@v3
        with:
          name: ios_build
          path: ios_build
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Upload IPA
        uses: wzieba/Firebase-Distribution-Github-Action@vmaster
        with:
          appId: 1:420295022617:ios:a8368f9757aec30e4d3288
          token: 1//069zeH2EL8NWICgYIARAAGAYSNwF-L9IrWy9_03-PKJVkSJyV1zAoSmkZKoLlecYkqXcQedU1EshrwoBW7jCFX5t78aosc8QhONA
          group: testers
          file: ios_build/Release-iphoneos/Runner.ipa