name: Web workflow

on:
  workflow_call:

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get dependencies
        run: flutter channel beta
      - run: flutter upgrade
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter create .
      - run: flutter build web -t lib/main_dev.dart
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web_build
          path: build/web

  deploy:
    name: Deploy app
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: web_build
          path: web_build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: '${{secrets.FIREBASE_TOKEN}}'
